### ISSUE TITLE
SLA querys have different results

### ISSUE THREAD

**Issue by krobar1** [rubrikinc/rubrik-powershell-sdk#6]
I was looking at the commands to list all of the SLAs and found 2 ways to get the data.  On closer inspection the commands return different results.  Do you know why these commands return different results?

PS C:\Users\jwebb6> (Invoke-RscQuerySla).Nodes.count
131
PS C:\Users\jwebb6> (Invoke-Rsc "query {clusterSlaDomainConnection{nodes{name,id}}}").Nodes.count 
491
PS C:\Users\jwebb6>

**Comment by rynardtspies** [comment]
Hi @krobar1 

I think that's due to the way the cmdlet handles defaults.

It looks like the `Invoke-RscQuerySla` cmdlet returns a list of Global SLAs (RSC-Managed). Try the following:

Get a list of Global SLAs
`Invoke-RscQuerySla` or `Invoke-RscQuerySla -GlobalFilterList`

Now try getting a list of Cluster SLAs
`Invoke-RscQuerySla --ClusterDomainList`

Let me know if that returns the correct numbers.

Thanks

Rynardt

**Comment by Freakwncy** [comment]
Ok. That verifies our understanding of which SDK pulls what information.

PS C:\temp> Invoke-RscquerySla -GlobalFilterList

Count Edges Nodes                                                                                                                             PageInfo
----- ----- -----                                                                                                                             --------
  131       {2023-01-11T18-54-15Z_Uruaguay_LATAM_USTRY14RBRKBU01, 8 Weeks Retention, AMUS_CKU1_NDB_UDB_LO_0100, AMUS_CKU1_PDB_UDB_LO_YEARLY…} RubrikSecurityCloud.Types.PageInfo

PS C:\temp> Invoke-RscquerySla -ClusterDomainList

Count Edges Nodes                                                              PageInfo
----- ----- -----                                                              --------
  491       {1102_testvol_sla, 7day_Repli_Retention, AArgentina Temp, AATemp…} RubrikSecurityCloud.Types.PageInfo

PS C:\temp>

**Comment by guirava** [comment]
Scrubbing old issues ... I believe this is resolved, please re-open if not.
