### ISSUE TITLE
Get-RscCluster shows old info

### ISSUE THREAD

**Issue by SahFari** [rubrikinc/rubrik-powershell-sdk#71]
Ran Get-RscCluster after the upgrade to CDM 8.13-p7. 

The result showed the correct version, but showed old info as well: SystemStatusMessage : 1 Disk Down.

We had replaced that faulty disk a week before the upgrade. Both I and Rubrik Support checked if we have a new disk that needs to be replaced, we don't. 

PauseStatus         : NOT_PAUSED
Status              : CONNECTED
SubStatus           : DEFAULT
SystemStatus        : OK
Type                : ON_PREM
Id                  : xxxxx
Name                : xxxxx
SystemStatusMessage : 1 Disk Down.
Version             : 8.1.3-p7-25298

**Comment by clumnah** [comment]
Please open a Support ticket and work directly with them on this. I will not have a way to reproduce this in our lab at all. We will need Support to look at logs to determine the root cause here. The SDK is returning back the info from the back end API and database. The SDK is not manipulating any data.

**Comment by SahFari** [comment]
Sure, I will reopen the case (00589181) I opened 2024-Apr-02 13:49:11
Resolution Details

log issues/bugs in the Git link directly instead of reaching out to support - https://github.com/rubrikinc/rubrik-powershell-sdk/issues

**Comment by clumnah** [comment]
I have already reached out to the support tech and I am awaiting their feedback.
